- src/main/scala/fundamentals/level03/ExceptionExercises.scala
- src/main/scala/fundamentals/level03/Exceptions2EitherExercises.scala
first cut of the exception exercises. Let me know if you think these are useful or whether we should not include them at all. If you're happy with this, I'll submit the Either version of the same problem.
> add ExceptionExercises

- src/test/scala/fundamentals/level03/ExceptionExercisesTest.scala
- src/test/scala/fundamentals/level03/Exceptions2EitherExercisesTest.scala
> Add exception tests

- src/main/scala/fundamentals/level03/OptionExercises3.scala
- src/test/scala/fundamentals/level03/OptionExercises3Test.scala
I'll add tests once you've given the thumbs up.
I reckon we make this easy for people to fill in.
We can test them on for-comprehension in Either and Try.
> Add OptionExercises3 for for-comprehension examples.

- README.md
I think I might be missing some steps to add the Scala SDK and JDK?
> Add IntelliJ setup instructions

- src/main/scala/fundamentals/level02/ListExercises.scala
- src/main/scala/fundamentals/level03/OptionExercises1.scala
- src/main/scala/fundamentals/level03/OptionExercises2.scala
- src/main/scala/fundamentals/level03/TryExercises.scala
Need to figure out how to do the same for Either.
> Add pattern matching notes for List, Option and Try.

- src/main/scala/fundamentals/level02/ListExercises.scala
- src/main/scala/fundamentals/level02/TypesExercises.scala
- src/main/scala/fundamentals/level03/OptionExercises1.scala
- src/main/scala/fundamentals/level03/OptionExercises2.scala
- src/main/scala/fundamentals/level03/TryExercises.scala
- src/test/scala/fundamentals/level02/TypesExercisesTest.scala
1. `showPerson1` introduces pattern matching early
2. `showPerson2` solves it by calling methods on `person` in string interpolation
3. Added `showWallet` so students can pick one of the two ways they solved `showPerson` to solve a new problem
> Introduce pattern matching early

- README.md
> update README with more instructions

- src/main/scala/fundamentals/level03/ForComprehension.md
https://github.com/wjlow/intro-to-scala/issues/19
> Examples of using for comprehension

- src/main/scala/fundamentals/level02/ListExercises.scala
> add ListExercises updates

- src/main/scala/fundamentals/level01/IntroExercises.scala
- src/main/scala/fundamentals/level02/TypesExercises.scala
- src/test/scala/fundamentals/level02/TypesExercisesTest.scala
> Intro and Type exercises updates

- src/main/scala/fundamentals/level02/TypesExercises.scala
- src/test/scala/fundamentals/level02/TypesExercisesTest.scala
Move default test case before flashing.
> Add additional test for flashing

- src/main/scala/fundamentals/level03/ExceptionExercises.scala
- src/main/scala/fundamentals/level03/Exceptions2EitherExercises.scala
- src/test/scala/fundamentals/level03/ExceptionExercisesTest.scala
> fix issues with exception-related content

- src/main/scala/fundamentals/level02/TypesExercises.scala
- src/main/scala/fundamentals/level03/OptionExercises1.scala
- src/main/scala/fundamentals/level03/OptionExercises2.scala
- src/main/scala/fundamentals/level03/OptionExercises3.scala
- src/test/scala/fundamentals/level03/NullExercisesTest.scala
- src/test/scala/fundamentals/level03/OptionExercises1Test.scala
> Option null updates

- src/main/scala/fundamentals/level03/ExceptionExercises.scala
> Add hint for createPerson to use getName and getAge

- src/main/scala/fundamentals/level03/NullExercises.scala
- src/test/scala/fundamentals/level03/NullExercisesTest.scala
> disallow creation of an invalid person

- src/main/scala/fundamentals/level02/ListExercises.scala
- src/test/scala/fundamentals/level02/ListExercisesTest.scala
https://github.com/wjlow/intro-to-scala/issues/62
> Add sortBy exercise to List to prepare for LogParser

- src/main/scala/fundamentals/level04/LogParser.scala
- Mention commenting out of the `import Types._ contents`
- Add question about what to do in a situation where the fileContent has empty lines
- Moving the *difficult* question at the bottom as a bonus question
> Update LogParser Steps based on feedback

- src/main/scala/fundamentals/level01/IntroExercises.scala
- src/test/scala/fundamentals/level01/IntroExercisesTest.scala
https://github.com/wjlow/intro-to-scala/issues/78
> Remove curry exercise

- src/main/scala/fundamentals/level03/NullExercises.scala
- src/main/scala/fundamentals/level03/OptionExercises1.scala
https://github.com/wjlow/intro-to-scala/issues/76
https://github.com/wjlow/intro-to-scala/issues/77
> Add green and yellow to traffic light examples

- src/main/scala/fundamentals/level02/TypesExercises.scala
- src/test/scala/fundamentals/level02/TypesExercisesTest.scala
https://github.com/wjlow/intro-to-scala/issues/72
> Remove frequency from Flashing to make the exercise simpler but still show exhaustiveness check.

- src/main/scala/fundamentals/level04/LogParser.scala
- src/test/scala/fundamentals/level04/LogParserTest.scala
The hints should be good enough.
> Remove findLatestError. No time for bonus questions.

- src/main/scala/fundamentals/level02/ListExercises.scala
https://github.com/wjlow/intro-to-scala/issues/55
> Add more hints to deconstructing tuples

- src/test/scala/fundamentals/level03/ExceptionExercisesTest.scala
> add boundary tests for age

- src/main/scala/fundamentals/level02/ListExercises.scala
- src/test/scala/fundamentals/level02/ListExercisesTest.scala
https://github.com/wjlow/intro-to-scala/issues/88
> Removing takeWhile exercise from List

- src/main/scala/fundamentals/level03/ExceptionExercises.scala
It wasn't clear which list you're meant to work on.
Since we've got `collect` skeletons below this, might as well add a `filter` skeleton. Also less brain power to remember how to use `case` in `filter`.
> Add skeleton to validPairs

- src/main/scala/fundamentals/level03/ExceptionExercises.scala
- src/main/scala/fundamentals/level03/Exceptions2EitherExercises.scala
- src/test/scala/fundamentals/level03/Exceptions2EitherExercisesTest.scala
> add clues, update docs

- src/main/scala/fundamentals/level04/LogParser.scala
Like we discussed on Friday, I'm adding this question in.
> Add empty line question to parseLogFile

- src/main/scala/fundamentals/level02/ListExercises.scala
- src/main/scala/fundamentals/level02/TypesExercises.scala
> updated doco

- src/main/scala/fundamentals/level03/ExceptionExercises.scala
- src/main/scala/fundamentals/level03/Exceptions2EitherExercises.scala
Replacing `collect` with `map` and `flatten`. Since both `map` and `flatten` are covered before this it should be much easier and introducing something like `collect`. The only down side is explaining `swap` but that's very easy.
> remove collect and replace with map and flatten

- src/main/scala/fundamentals/level03/ExceptionExercises.scala
- src/main/scala/fundamentals/level03/Exceptions2EitherExercises.scala
- src/test/scala/fundamentals/SimpleReporter.scala
> simplify with collect!

- src/main/scala/fundamentals/level03/Exceptions2EitherExercises.scala
- src/test/scala/fundamentals/level03/Exceptions2EitherExercisesTest.scala
Just realised that we didn't have any pattern matching exercises on Either. Added for consistency with the other modules.
> add pattern matching exercise

- build.sbt
- src/main/scala/fundamentals/level03/Exceptions2EitherExercises.scala
- src/test/scala/fundamentals/level03/Exceptions2EitherExercisesTest.scala
> add map and flatMap exercises

- README.md
Finally had a chance to review the course. Really good! Well done to everyone involved in putting this together, and especially @wjlow for kicking it off. I know how much work these take to build.
I propose some very minor tweaks
- Test if java 8 already present since thats likely
- De-emphasise particular version of SBT, since its versioned per project and that's really cool and a bit atypical for build tools; dont want to set wrong habits of thinking they have to upgrade sbt tool all the time.
> Minor doc tweaks

- src/main/scala/fundamentals/level02/ListExercises.scala
Few people have been confused about how to fold it.
> Add more hints to solving "min". 

- cheat-sheet.md
Added some concepts to the cheat sheet
> cheat-sheet WIP

- src/main/scala/fundamentals/level02/TypesExercises.scala
- src/test/scala/fundamentals/level02/TypesExercisesTest.scala
One less thing to explain and also not that important for the purpose of this course.
This will make it easier for candidates when they build their own ADTs in `LogParser`.
https://github.com/wjlow/intro-to-scala/issues/126
> Remove companion object for TrafficLight

- README.md
Removing morning tea (no catering this time!) which means we gotta have lunch earlier at 12pm otherwise people would starve.
Giving more time for `LogParser` so we can have a less abrupt end to the training.
Switching Sanj and Felipe's modules because Sanj is away day 2.
> Update schedule for upcoming run.

- src/main/scala/fundamentals/level01/IntroExercises.scala
- src/test/scala/fundamentals/level01/IntroExercisesTest.scala
> add exercise and test for currying

- src/main/scala/fundamentals/level02/TypesExercisesNotes.md
I've been toying around with the idea of adding *notes* as markdown code-snippets directly in the modules. This make it easy to access for the students and they can easily copy-and-paste where necessary.
> Add notes to TypesExercises

- cheat-sheet.md
> add notes on FP

- cheat-sheet.md
> remove semicolon from for-comp

- cheat-sheet.md
> add info on classes, objects, traits etc

- cheat-sheet.md
Adding a short note as it came up after a discussion around `List` construction.
> Add note about companion objects.

- src/main/scala/fundamentals/level03/ForComprehension.md
- src/main/scala/fundamentals/level03/OptionExercises2.scala
- src/main/scala/fundamentals/level03/OptionExercises3.scala
- src/test/scala/fundamentals/level03/OptionExercises2Test.scala
- src/test/scala/fundamentals/level03/OptionExercises3Test.scala
I think we can afford one more exercise!
This teaches that you can call functions when you `yield` in a for comprehension.
> Add another exercise to Option2 and 3

- src/main/scala/fundamentals/level03/ExceptionExercises.scala
- src/test/scala/fundamentals/level03/ExceptionExercisesTest.scala
Minor mismatch between the exercise description and the specs.
> Exception exercise spec missing

- cheat-sheet.md
- src/main/scala/fundamentals/level04/LogParser.scala
I've added an extra hint for the LogParser exercise which I think will help the students. I've also included an example on pattern matching an `Array` to the cheatsheet which will help.
> add hint on how to pattern match on Array

- src/main/scala/fundamentals/level03/TryExercises.scala
- src/main/scala/fundamentals/level04/LogParser.scala
- src/test/scala/fundamentals/level04/LogParserTest.scala
- Provide the start of a suggested implementation
> Make parseLog more approachable.

- README.md
> Add links to ScalaTest and Scalactic scaladoc

- src/main/scala/fundamentals/level01/IntroExercises.scala
> Add thought exercise around side effects

- src/main/scala/fundamentals/level01/IntroExercises.scala
- src/test/scala/fundamentals/level01/IntroExercisesTest.scala
> Add pair exercises as per 158

- README.md
> Add link to Delight

- src/main/scala/fundamentals/level02/ListExercises.scala
- src/test/scala/fundamentals/level02/ListExercisesTest.scala
So I've added some extra validation rules and beefed up the tests to cover almost all cases.
> added updated version of showEveryNthPerson

- src/main/scala/fundamentals/level03/TryExercises.scala
> Make mkEmployee fail initially

- src/main/scala/fundamentals/level03/TryExercises.scala
- src/test/scala/fundamentals/level03/TryExercisesTest.scala
> Add try to option tests

- src/main/scala/fundamentals/level03/Collect.md
- src/main/scala/fundamentals/level03/Either.md
- src/main/scala/fundamentals/level03/Try.md
> Add more notes!

- src/main/scala/fundamentals/level02/ListExercises.scala
- src/test/scala/fundamentals/level02/ListExercisesTest.scala
I think these are good exercises because people get to compare a mutable version and the immutable version.
The solutions are:
```
def getNames(persons: List[Person]): List[String] =
persons.map(_.name)
def getAdults(persons: List[Person]): List[Person] =
persons.filter(_.age >= 18)
def reverseList[A](xs: List[A]): List[A] =
xs.foldLeft(List.empty[A])((acc, x) => x :: acc)
```
Don't merge until @ashokkumar is happy with it :)
> Add exercises for rewriting mutable code as immutable

- src/main/scala/fundamentals/level02/ListExercises.scala
- src/test/scala/fundamentals/level02/ListExercisesTest.scala
> Added sublist exercise

- cheat-sheet.md
> Add structure of a function to cheatsheet

- cheat-sheet.md
[Git Issue](https://github.com/wjlow/intro-to-scala/issues/182)
Add definitions for Functor, Applicative and Monad (Taken from the Applied-Scala Wiki)
> Include definitions for Functor, Applicative and Monad to cheat-sheet

- src/main/scala/fundamentals/level03/Exceptions2EitherExercises.scala
Bringing the two exercises together to show the comparison side by side
> Reorder createPerson exercises together

- .travis.yml
- build.sbt
- delight.sbt
- docker-compose.yml
- project/build.properties
- project/plugins.sbt
This upgrades the course to Scala 2.13. I assumed we don't want to cross compile against 2.12.
> Upgrade to Scala 2.13

- .travis.yml
- src/main/scala/introcourse/level04/OptionExercises3.scala
When I teach this, I often have to copy the flatMap versions of the solutions from OptionExercises2 into this file so we can compare the flatMap versions with the for comprehension versions.
It makes sense to just have the solutions here so I don't have to do that.
> Fill out Option3 with flatMap solutions, so it's more obvious how to change it to a for comprehension.

- README.md
Brew got an update so this error didn't work for me! I just added a quick snippet into the README for those who experience the same problem.
> Updated README: new Homebrew changes 🍻

- README.md
- auto/dev-environment
- build.sbt
- docker-compose.yml
- project/build.properties
- project/plugins.sbt
- src/test/scala/introcourse/level01/IntroExercisesTest.scala
- src/test/scala/introcourse/level02/TypesExercisesTest.scala
- src/test/scala/introcourse/level03/ListExercisesTest.scala
- src/test/scala/introcourse/level04/NullExercisesTest.scala
- src/test/scala/introcourse/level04/OptionExercises1Test.scala
- src/test/scala/introcourse/level04/OptionExercises2Test.scala
- src/test/scala/introcourse/level04/OptionExercises3Test.scala
- src/test/scala/introcourse/level05/EitherExercisesTest.scala
- src/test/scala/introcourse/level05/ExceptionExercisesTest.scala
- src/test/scala/introcourse/level06/TryExercisesTest.scala
- src/test/scala/introcourse/level07/LogParserTest.scala
About to run this training and everyone here is now on jdk 11.
Bumping the version so people don't need to install an older version.
Feel free to ignore though if you aren't ready to bump to jdk 11.
> Update to JDK 11 and sbt 1.3.8

- .travis.yml
- build.sbt
- docker-compose.yml
- project/build.properties
- project/plugins.sbt
We are about to run the training again at Zendesk.  Bumping deps
> Bump sbt / scala / scalatest

- src/main/scala/introcourse/level02/TypesExercises.scala
- src/main/scala/introcourse/level04/NullExercises.scala
- src/main/scala/introcourse/level04/OptionExercises1.scala
- src/test/scala/introcourse/level02/TypesExercisesTest.scala
This addresses: https://github.com/wjlow/intro-to-scala/issues/205
> Switch from changeName to changeAge so you must specify the param in .copy(age = 123)

- src/main/scala/introcourse/level02/TypesExercisesNotes.md
- src/main/scala/introcourse/level04/ForComprehension.md
- src/main/scala/introcourse/level05/Collect.md
- src/main/scala/introcourse/level06/Try.md
Add `scala` to enable syntax highlighting in markdown :)
> Add syntax highlighting for code blocks

- .gitignore
- .travis.yml
- docker-compose.yml
- project/build.properties
- project/plugins.sbt
> Bump versions

- src/main/scala/introcourse/level07/LogParser.scala
- src/test/scala/introcourse/level07/LogParserTest.scala
- src/test/scala/introcourse/level07/Types.scala
- Prefill parseIntOption to speed up the exercise
- Rework the ADT stubs for ease of use
This will hopefully make students' lives a little easier.
> Minor improvements to LogParser

- build.sbt
- project/build.properties
- project/plugins.sbt
- src/main/scala/introcourse/level05/EitherExercises.scala
and several other updates. I also had to fix some inconsistent indentation that Scala 3 was unhappy with.
> Update to Scala 3

- README.md
- cheat-sheet.md
- src/main/scala/introcourse/level02/TypesExercises.scala
- src/main/scala/introcourse/level03/package.scala
- src/main/scala/introcourse/level04/package.scala
- src/main/scala/introcourse/level05/EitherExercises.scala
- src/main/scala/introcourse/level06/Try.md
- src/main/scala/introcourse/level06/TryExercises.scala
- src/main/scala/introcourse/level07/LogParser.scala
- src/main/scala/introcourse/level07/Main.scala
- src/test/scala/introcourse/level01/IntroExercisesTest.scala
- src/test/scala/introcourse/level02/TypesExercisesTest.scala
- src/test/scala/introcourse/level03/ListExercisesTest.scala
- src/test/scala/introcourse/level04/NullExercisesTest.scala
- src/test/scala/introcourse/level04/OptionExercises1Test.scala
- src/test/scala/introcourse/level04/OptionExercises2Test.scala
- src/test/scala/introcourse/level04/OptionExercises3Test.scala
- src/test/scala/introcourse/level05/EitherExercisesTest.scala
- src/test/scala/introcourse/level05/ExceptionExercisesTest.scala
- src/test/scala/introcourse/level06/TryExercisesTest.scala
- src/test/scala/introcourse/level06/TryTestTypes.scala
- src/test/scala/introcourse/level07/LogParserTest.scala
- src/test/scala/introcourse/level07/Types.scala
Also changed the import style from `._` to `.*`
> Switch to Scala 3 enum style
