src/main/scala/fundamentals/level03/ExceptionExercises.scala
src/test/scala/fundamentals/level03/ExceptionExercisesTest.scala

- By adding a tuple with error in name and age makes `collectErrors` implementation more complicated.
- added extra test while trying to prove the case and found it useful to have as `zip` ignores values when list sizes are different.

Improve exception exercises, add double errored entry.

---

src/main/scala/fundamentals/level03/TryExercises.scala
src/test/scala/fundamentals/level03/TryExercisesTest.scala

As we have a for comprehension exercise, felt that we should introduce .map to Try before that. 
I thought of introducing 
```
def intOperation(str: String, f: Int => Int): Try[Int] = ???
```
then thought it might be too difficult, what's your thought on that @wjlow @sanjivsahayamrea

Add .map example to Try

---

src/main/scala/fundamentals/level03/ExceptionExercises.scala
src/test/scala/fundamentals/level03/ExceptionExercisesTest.scala

add more hints

---

src/main/scala/fundamentals/level03/ForComprehension.md

As discussed, this is a little confusing for beginners and not necessary to understand for comprehension at a basic level.

Remove for-comp example for List

---

src/main/scala/fundamentals/level03/ExceptionExercises.scala
src/test/scala/fundamentals/level03/ExceptionExercisesTest.scala

I'm removing `validPairs` because it is not really used in `createValidPeople` or `collectErrors`. Also the `Exceptions2EitherExercises` don't have a `validPairs` equivalent.

remove valid pairs

---

src/main/resources/logfile.csv

Not a big deal, but currently the WARN line in `logfile.csv` will probably be parsed as an `UnknownLog`.
https://github.com/wjlow/intro-to-scala/issues/125

Add timestamp to warn log in logfile.csv

---

src/main/scala/fundamentals/level04/LogParser.scala
src/test/scala/fundamentals/level04/LogParserTest.scala

While working through the exercises with someone during a coaching session, I found that it would give the exercise more purpose if it can be reused later on.
The `showErrorsOverSeverity` exercise can re-use `getErrors` now.
https://github.com/wjlow/intro-to-scala/issues/128

Change getUnknowns exercise to getErrors so it can be re-used later.

---

src/test/scala/fundamentals/level01/IntroExercisesTest.scala

The **bar** test was using **foo**. Not sure how we missed this before. Also changed the names
of the tests a little so there was no repetition.

fix incorrect test

---

src/main/scala/fundamentals/level02/ListExercises.scala
src/test/scala/fundamentals/level02/ListExercisesTest.scala

Instead of teaching zipping, this ends up being an index-counting exercise. The test cases were also non-exhaustive and only covered the case where N=2. 
We should come up with a better exercise for zipping next time. For now, I reckon we remove this entirely.

Removing showEveryNthPerson.

---

src/test/scala/fundamentals/level01/IntroExercisesTest.scala

Triangulate `add` tests so we can't just use the value `3` as an implementation and have it pass!

add more tests around add so it can't be duped

---

src/test/scala/fundamentals/level02/ListExercisesTest.scala

Super minor, but got confused while doing this exercise because the description didn't match the expectation in the spec. Turns out the exercise text states that the first person in the list should be returned, but this isn't reflected in the spec description.

Fix inaccurate listing spec description

---

src/main/scala/fundamentals/level02/ListExercises.scala

We need to use matching on pairs for the `personWithIndex` exercise. Moving instructions there.

Move instructions on pairs to where it is first used

---

README.md

`java8` doesn't work anymore in `brew cask`: https://github.com/Homebrew/homebrew-cask/issues/58311
This fixes it using openjdk8

Update Java8 install instructions

---

src/test/scala/fundamentals/level03/Exceptions2EitherExercisesTest.scala

https://github.com/wjlow/intro-to-scala/issues/180
- Prevent getAge from allowing 0, which breaks more exercises later on

Add additional test for Exceptions2Either

---

src/test/scala/introcourse/level01/IntroExercisesTest.scala

with 2, the implementation could use square rather than times 2 and still pass (1 of the peeps that tried this last week had an incorrectly implemented solution which passed the test)

Made test more robust

---

src/main/scala/introcourse/level07/LogParser.scala

This is so when they pattern match on `case KnownLog(Error(severity..`, there is no conflicting variable name.

Rename severity parameter to minimumSeverity

---

src/main/scala/introcourse/level01/IntroExercises.scala

When you do `addCurried(x)(y)`, it's not immediately obvious that you can partially apply `addCurried`

Expand add5 to a 2-step process to show partial application

---

src/main/scala/introcourse/level01/IntroExercises.scala
src/test/scala/introcourse/level01/IntroExercisesTest.scala

These hints should help the instructors to remember to cover both the getters and the pattern matching syntax.

Add hints to `fst`, rename `fst` and `snd` to `first` and `second`.

---

src/test/scala/introcourse/level04/OptionExercises1Test.scala

Three people were trying to work out why their tests were failing but the 'bob' was placed in the string properly. The backticks just confused people.
This PR might break the solutions branch

Removed backtick style quotes around test for bob in a string.

---

src/main/scala/introcourse/level05/EitherExercises.scala
src/test/scala/introcourse/level05/EitherExercisesTest.scala

I've been thinking about this exercise [exercise](https://github.com/wjlow/intro-to-scala/blob/master/src/main/scala/introcourse/level05/EitherExercises.scala#L149), where it feels like you're almost repeating the message from the error itself. Leads to some students wondering why we have to retype the message, instead of trying to extract it from the error somehow. 
📦 
- This change makes it so only the invalid value itself is contained in the error
- Leave interpreting the error to the createPersonAndShow function

Remove messages from error ADT

---

src/main/scala/introcourse/level04/NullExercises.scala

It's weird and awkward and unnecessary.

Remove the thought exercise for "mean".

---

src/test/scala/introcourse/level07/LogParserTest.scala

This is so that they can simply remove the `Types.*` import and things will still compile.
With the change from sealed traits to enums, the namespacing of the constructors changed.

Import the constructors of the ADTs that learners will define in this exercise
